sinProject-Inc/sinpro-dev

README.md
=> Update a readme file #13

docs/40-testing/10-vitest.md, docs/40-testing/20-playwright.md, src/lib/docs/markdown.ts
=> Adjust the link to the code #21

.github/ISSUE_TEMPLATE/custom.md, .github/pull_request_template.md
=> Update issue template #12

src/lib/app.css
=> Change the tab size of the code block #31

src/lib/components/github_link.svelte, src/lib/components/icons/twitter_icon.svelte, src/lib/components/menu_items_sub.svelte, src/lib/components/nav_item.svelte, src/lib/components/nav_item_tab.svelte, src/lib/components/navbar.svelte, src/lib/components/twitter_link.svelte
=> Change the menu #17

package-lock.json, package.json
=> Release v0.61.0 #35

docs/10-company-information/10-portfolio.md, src/routes/docs/[slug]/+page.svelte
=> Update the Portfolio page #19

static/sitemap.xml
=> Rebuild a sitemap.xml #15

package-lock.json, package.json
=> Release v0.62.0 #41

docs/35-code-style/30-eslint.md
=> Add: Using ESLint with Svelte #44

.eslintrc.cjs, .vscode/settings.json, docs/20-dev-environment/20-vscode-workspace-settings.md, docs/35-code-style/30-eslint.md, e2e/docs.spec.ts
=> Add the tabsize rule #49

docs/30-clean-code/15-format.md
=> Add file name rules #20

docs/10-company-information/10-portfolio.md, docs/10-company-information/30-services.md
=> Fix English #52

docs/30-clean-code/15-format.md, docs/35-code-style/30-eslint.md
=> Fix English #54

docs/50-git/43-github_repository_settings.md
=> Update the wording in the GitHub Repository Settings #56

docs/30-clean-code/40-objects-and-data-structures.md
=> Prefix private members with an underscore #60

docs/30-clean-code/20-variables.md
=> Prefer const #62

docs/20-dev-environment/15-chrome-extensions.md
=> Add Chrome Extensions #64

docs/20-dev-environment/15-chrome-extensions.md
=> Add: Video Speed Controller to Chrome Extensions #66

docs/40-testing/10-vitest.md, docs/40-testing/20-playwright.md
=> Fix dead links #69

package-lock.json, package.json
=> Release 0.64.0

docs/20-dev-environment/95-keyboard-shortcuts.md
=> Keyboard Shortcuts #70

docs/70-team-sinproject/99-docs-history.md
=> Add releases to history #73

src/routes/docs/mobile_docs_side_bar.svelte
=> Adjust docs side bar #76

docs/60-server/40-updating-the-server.md
=> Update Announcement links #81

docs/20-dev-environment/90-tailwind-css.md
=> Add Install Tailwind CSS with SvelteKit #83

package-lock.json, package.json
=> Release 0.65.0

docs/80-talk/30-app-structure.md
=> Update App Structure links #105

docs/50-git/30-github-issues.md
=> Write issue titles in affirmative form #91

docs/20-dev-environment/95-keyboard-shortcuts.md
=> Add three shortcuts to default the display #126

src/lib/app.css, src/lib/components/github_link.svelte, src/lib/components/nav_item.svelte, src/lib/components/navbar.svelte, src/lib/components/twitter_link.svelte, src/lib/components/version_footer.svelte, src/routes/+layout.svelte, src/routes/+page.svelte, src/routes/docs/+layout.svelte
=> Make it possible to press the PUSH MENU BUTTON #86

static/abs.txt
=> Implement AdSense #135

static/abs.txt, static/ads.txt
=> 135 implement adsense

package-lock.json, package.json
=> Release v0.66.0 #137

docs/10-company-information/30-services.md
=> Delete sentences in Office Space #134

.vscode/settings.json, src/lib/docs/markdown.ts, src/lib/docs/markdown_code_element.ts
=> Refactor markdown.ts #143

src/lib/docs/markdown.ts, src/lib/git/create_git_branch.ts, src/routes/docs/[slug]/+page.server.ts
=> Refactor src/routes/docs/[slug]/+page.server.ts #146

docs/50-git/40-github-pull-requests.md
=> Add praise for what was good in the PR review. #99

src/lib/view/os_info.ts
=> Refactor src/lib/view/os_info.ts #150

src/hooks.server.ts
=> Fix duplicate on hooks.server.ts #168

.vscode/extensions.json, docs/20-dev-environment/30-vscode-workspace-extensions.md
=> Add the CodeMetrics extension #153

src/routes/docs/[slug]/+page.svelte
=> Self URL Link to Docs Page Title #142

docs/40-testing/20-playwright.md
=> Update Playwright's code #170

src/routes/+layout.svelte, src/routes/docs/+layout.svelte
=> 背景画像が変更されるタイミングを調整する #96

.vscode/extensions.json, .vscode/settings.json, docs/20-dev-environment/30-vscode-workspace-extensions.md
=> Add the highlighting extensions #164

src/lib/docs/markdown.ts, src/lib/docs/search_index.ts, src/routes/docs/+layout.server.ts, src/routes/docs/[slug]/+page.server.ts, svelte.config.js
=> Change fs.readFileSync() to fs.promises.readFile() #93

docs/60-server/20-pm2.md
=> Insert sinpro-dev's Ecosystem File before Talk's Ecosystem File #160

src/lib/docs/search_result_context.ts
=> 173 refactor searchresultcontext.ts

package-lock.json, package.json
=> Release v0.67.0 #181

e2e/docs.spec.ts
=> Refactor docs.spec.ts #184

playwright.config.ts
=> Refactor playwright.config.ts #187

src/hooks.server.ts
=> Refactor hooks.server.ts #189

src/lib/app/logger.ts
=> Refactor logger.ts #191

src/lib/git/create_git_branch.ts
=> Refactor create_git_branch.ts #193

src/lib/docs/markdown.ts
=> Refactor markdown.ts #196

tailwind.config.cjs
=> Refactor tailwind.config.cjs #199

src/service-worker.js
=> Fix TypeError on the top page #107

e2e/docs.spec.ts
=> Refactor docs.spec.ts #208

docs/70-team-sinproject/30-slack.md
=> Add Slack settings #179

e2e/docs.spec.ts, src/routes/docs/side_bar.svelte
=> Adjust the playwright tests #219

.github/workflows/ci.yml, .github/workflows/cr-akiojin.yml, .github/workflows/cr-anc95.yml
=> Name the GitHub Action jobs #217

package-lock.json, package.json
=> Release v0.68.0 #222

src/routes/docs/[slug]/ad_sense.svelte
=> Update AdSense ads after navigating #229

src/app.html
=> Implement Google Analytics #231

.vscode/extensions.json, docs/20-dev-environment/30-vscode-workspace-extensions.md
=> Add VSCode Extensions #183

docs/70-team-sinproject/50-funny-apps.md
=> Funny Apps #101

src/lib/docs/markdown_code_element.test.ts
=> Refactor markdown_code_element.test.ts #234

src/lib/docs/current_page_store.test.ts
=> Refactor current_page_store.test.ts  #237

src/lib/general/sentence_service.test.ts
=> Refactor sentence_service.test.ts #239

src/routes/docs/[slug]/+page.svelte
=> Display the LINE share icon only when viewing on a mobile device. #227

playwright.config.ts, src/lib/components/share_to_facebook.svelte, src/lib/components/share_to_x.svelte
=> Change facebook link #226

src/lib/app/app.ts, src/routes/+page.svelte
=> Change the top page meta description #251

package-lock.json, package.json
=> Release v0.69.0 #253

src/routes/docs/[slug]/ad_sense.svelte
=> Fix loading progress bar behavior #261

docs/10-company-information/20-about.md, src/routes/docs/[slug]/ad_sense.svelte
=> Improve PageSpeed and Lighthouse scores #263

docs/20-dev-environment/15-chrome-extensions.md
=> Add Chrome Extension #257

docs/10-company-information/10-portfolio.md, docs/10-company-information/20-about.md, docs/10-company-information/30-services.md, src/app.html, src/routes/docs/[slug]/ad_sense.svelte, src/routes/docs/[slug]/on_this_page.svelte
=> Improve PageSpeed and Lighthouse scores #266

.github/workflows_/cr-anc95.yml
=> Fix Code Review by anc95 GitHub Action #242

.github/workflows/cr-akiojin-gpt-4.yml, .vscode/settings.json, docs/50-git/50-github-actions.md
=> Use gpt4 for code review by akiojin #269

.github/pull_request_template.md
=> Update PR Template #268

.github/pull_request_template.md
=> Update PR template #273

.github/workflows/cr-akiojin-gpt-4.yml, sample.md
=> Verify if the newly created files have been checked #284

package-lock.json, package.json
=> Release v0.70.0 #287

.github/pull_request_template.md
=> Update PR template #289

docs/20-dev-environment/80-chatgpt-prompts.md, src/lib/app/app.test.ts, src/lib/app/app.ts, src/lib/app/logger.test.ts, src/lib/docs/current_page_store.test.ts, src/lib/docs/markdown.test.ts, src/lib/docs/markdown_code_element.test.ts, src/lib/general/formatted_date.test.ts, src/lib/general/formatted_date.ts, src/lib/general/sentence_service.test.ts, src/lib/general/system.test.ts, src/lib/network/client_address.test.ts
=> Refactoring test codes using GPT-4 #291

docs/50-git/40-github-pull-requests.md
=> Add Merge pull request section to GitHub Pull Request Page #296

.github/ISSUE_TEMPLATE/custom.md
=> Update Issue Template #298

.github/pull_request_template.md
=> Update PR Template #299

docs/40-testing/10-vitest.md
=> Add a test.each sample to the Vitest page #307

package-lock.json, package.json
=> Release v0.71.0 #309

docs/50-git/10-git-branches-and-commits.md
=> Change the link within page Git Branches and Commits #312

.husky/pre-commit, docs/50-git/20-git-hooks.md
=> Prevent commits directory to main branch #318

src/lib/background/background.ts, src/lib/docs/markdown.ts, src/lib/docs/search_index.ts, src/lib/docs/search_result_context.ts, src/lib/network/client_address.test.ts, src/lib/network/client_hostname.ts, src/routes/+layout.svelte, src/routes/docs/+layout.svelte, src/routes/docs/[slug]/ad_sense.svelte, src/routes/docs/search_modale.svelte, src/scripts/create_git_branch.ts, tsconfig.json
=> Set tsconfig to strictest #320

docs/40-testing/20-playwright.md, playwright.config.ts, tests/docs.spec.ts
=> Configure Playwright #322

.github/workflows/ci.yml, .vscode/settings.json, docs/40-testing/10-vitest.md, docs/55-code-analytics/10-sonar-cloud-coverage.md, docs/55-code-analytics/meta.json, sonar-project.properties, vite.config.ts
=> Activate SonarCloud Coverage #324

docs/40-testing/10-vitest.md, docs/55-code-analytics/10-sonar-cloud-coverage.md, sonar-project.properties, vite.config.ts
=> Configure SonarCloud Test Coverage #329

sonar-project.properties, src/lib/network/client_address.test.ts
=> Add coverage exclusions to increase the test coverage #334

package-lock.json, package.json
=> Release v0.72.0 #338

docs/40-testing/10-vitest.md, src/lib/app/app.test.ts, src/lib/app/logger.test.ts, src/lib/docs/current_page_store.test.ts, src/lib/docs/markdown_code_element.test.ts, src/lib/general/formatted_date.test.ts, src/lib/general/sentence_service.test.ts, src/lib/general/system.test.ts, src/lib/network/client_address.test.ts, src/lib/stores.test.ts
=> Use it() function on Vitest code #340

.github/ISSUE_TEMPLATE/release.md
=> Update Release Tempalte #343

docs/35-code-style/10-tsconfig.md
=> Update a tsconfig document #350

package-lock.json, package.json
=> Release v0.73.0 #353

.github/pull_request_template.md
=> PR Template Modify who can merge into main branch #355

.vscode/settings.json
=> Change html format to Prettier #371

docs/20-dev-environment/10-macos-settings.md
=> Introducing Cursor #375
